import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "react-hot-toast";
import { isLoggedIn } from "./actions/auth-actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isSignedIn = await isLoggedIn();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar isSignedIn={isSignedIn} />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
